name: flutter_web_server
description: A web server to host flutter web application
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.1
  shelf: ^1.4.1
  shelf_gzip: ^4.1.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^1.1.2
  lints: ^3.0.0
  test: ^1.20.1